# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: bookstore
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080